#!/bin/bash
DATETIME=$(date '+%Y.%m.%d-%H.%M.%S')
LOG_PARSING_DIRECTORY=/net/isilonP/public/rw/homes/uni_adm/tmp/log_parsing/DATETIME
JSON_DIRECTORY=$LOG_PARSING_DIRECTORY/json
COLUMNS_DIRECTORY=$LOG_PARSING_DIRECTORY/columns
OFFSET_DIRECTORY=$LOG_PARSING_DIRECTORY/offset
FIELD_TO_VALUES_DIRECTORY=$LOG_PARSING_DIRECTORY/field_to_values
OUT_DIRECTORY=$LOG_PARSING_DIRECTORY/out
ERROR_DIRECTORY=$LOG_PARSING_DIRECTORY/error
LOG_FILE_LIST=$LOG_PARSING_DIRECTORY/log_file_list.txt
JSON_FILE_LIST=$LOG_PARSING_DIRECTORY/json_file_list.txt
LOG_DIRECTORY=/nfs/public/rw/homes/tc_uni01/uuw-stats/logs/